const tempGamesList = [
  {
    id: 12345,
    igdbid: 1234567,
    title: 'Persona 5',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1iea.jpg',
    description: 'Persona 5, a turn-based JRPG with visual novel elements, follows a high school student with a criminal record for a crime he didn\'t commit. Soon he meets several characters who share similar fates to him, and discovers a metaphysical realm which allows him and his friends to channel their pent-up frustrations into becoming a group of vigilantes reveling in aesthetics and rebellion while fighting corruption.',
    rating: 94.5,
    released: new Date('09/15/2016'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 1235, igdbid: 12346, name: 'Platform'}, {id: 4567, igdbid: 23456, name: 'RPG'}],
    website: 'http://www.atlus.com/persona5/home.html',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/hlev27g508rkq1prpghw.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/pm074uf0po31urbrjyxz.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/k9vp7u6khokwawwctcgc.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/gin55k9eyfq8udk0taym.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/tow7qunrq6rvwouracii.jpg'],
    platforms: [{id: 123, igdbid: 12345, name: 'PS4', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6e.png'}],
    ESRB: {id: 123, igdb:  12345, rating: 3, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_11.svg'},
    yearReleased: 2016,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 23456,
    igdbid: 2345678,
    title: 'The Legend of Zelda: Breath of the Wild',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/mievpzb9rbzzenmznvnr.jpg',
    description: 'Step into a world of discovery, exploration and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series. Travel across fields, through forests and to mountain peaks as you discover what has become of the ruined kingdom of Hyrule in this stunning open-air adventure.',
    rating: 95.5,
    released: new Date('03/03/2017'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 4567, igdbid: 23456, name: 'RPG'}],
    website: 'http://www.zelda.com/breath-of-the-wild/',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/ods1wksjfo9h0v7fpigo.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ayjm7juog9vitiwbfrcz.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/gcdqd20hi1wgmguu3reg.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/eirwofgnucvx7h87svr2.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/mftmubfp9ntwbreejfi7.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/qoytovwmzj70nufwxb2r.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/bf4ag3vxlfnv0nhhplga.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/mepn5qujlccdlkhfkwr8.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/tjlglyti9pi4cowyiact.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/vbs1btl6ts17zeos4g5v.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/djytg7kqip9d5dgekfew.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ngyp9tw3elpfdngwc00i.jpg'],
    platforms: [{id: 234, igdbid: 23456, name: 'Nintendo Switch', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6b.png'}],
    ESRB: {id: 234, igdb:  22345, rating: 1, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_9.svg'},
    yearReleased: 2017,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 23457,
    igdbid: 4345678,
    title: 'Ace Attorney Investigations 2',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/nz4t3kgz9w9nf0e9qumo.jpg',
    description: 'Gyakuten Kenji 2 (逆転検事 2 Gyakuten Kenji 2, lit. "Turnabout Prosecutor 2""), also referred to as "Ace Attorney Investigations 2" by Capcom staff, is the sequel to "Gyakuten Kenji" (known as "Ace Attorney Investigations: Miles Edgeworth" in English) and the sixth game in the "Ace Attorney" series of text adventure video games.',
    rating: 99.0,
    released: new Date('02/03/2011'),
    genres: [],
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/frgknqca1xyot7fyzw4j.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/cxf2bt9ejnkbeocuoym7.jpg' , 'https://images.igdb.com/igdb/image/upload/t_original/qx0ckbpgu5i0y7tmpxha.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/biza3bnqypn0zb3zljzt.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/zlotf0jcvnw6c4ldyzqa.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/nyoj0jhufbri0ql6fsin.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/v9fzxl9nggsfllmzeptj.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/frgknqca1xyot7fyzw4j.jpg'],
    platforms: [{id: 236, igdbid: 23457, name: 'Nintendo DS', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6r.png'}],
    yearReleased: 2011,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 29387,
    igdbid: 9834753,
    title: 'Stardew Valley',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/xrpmydnu9rpxvxfjkiu7.jpg',
    description: 'Stardew Valley is an open-ended country-life RPG! You’ve inherited your grandfather’s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home? It won’t be easy. Ever since Joja Corporation came to town, the old ways of life have all but disappeared. The community center, once the town’s most vibrant hub of activity, now lies in shambles. But the valley seems full of opportunity. With a little dedication, you might just be the one to restore Stardew Valley to greatness!',
    rating: 89.5,
    released: new Date('02/26/2016'),
    genres: [{id: 4569, igdbid: 23956, name: 'Indie'}, {id: 4567, igdbid: 23456, name: 'RPG'}, {id: 4268, igdbid: 23526, name: 'Simulator'}],
    website: 'http://www.stardewvalley.net/',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/rhxs1x9w5hf5kde2osf5.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/sw7rtba7p1xs77klsime.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/iwswpvxa9ytrpk8yjcyx.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ak7zmag7zztpqha1jjde.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/g1aakqbkp2quq0krqeky.jpg'],
    platforms: [{id: 234, igdbid: 23456, name: 'Nintendo Switch', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6b.png'}, {id:840, igdbid: 92330, name: 'Steam', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6i.png'}],
    ESRB: {id: 234, igdb:  22345, rating: 1, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_9.svg'},
    yearReleased: 2016,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 29398,
    igdbid: 9834773,
    title: 'Minecraft',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ml9.jpg',
    description: 'Minecraft is an open world game that has no specific goals for the player to accomplish, allowing players a large amount of freedom in choosing how to play the game however, there is an achievement system. The gameplay by default is first person, but players have the option to play in third person mode. The core gameplay revolves around breaking and placing blocks. The game world is essentially composed of rough 3D objects—mainly cubes—that are arranged in a fixed grid pattern and represent different materials, such as dirt, stone, various ores, water, and tree trunks. While players can move freely across the world, objects and items can only be placed at fixed locations relative to the grid. Players can gather these material blocks and place them elsewhere, thus allowing for various constructions.',
    rating: 83.0,
    released: new Date('10/07/2011'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 4568, igdbid: 23556, name: 'Arcade'}, {id: 4569, igdbid: 23956, name: 'Indie'}, {id: 4268, igdbid: 23526, name: 'Simulator'}, {id: 4478, igdbid: 23592, name: 'Strategy'}],
    website: 'https://minecraft.net/',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/vm8dthz69tuppu1pazjc.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/kvbwjprt8tnweegegv3u.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/risbtotrixghfy8o9wdj.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/cf4mbecc1blh5k3rlszr.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/ldeuxkt76th569psyzhq.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/c5ofbzndvfgpclfra7cq.jpg'],
    platforms: [{id: 202, igdbid: 23296, name: 'Xbox 360', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6z.png'}, {id:281, igdbid: 92019, name: 'PC', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/irwvwpl023f8y19tidgq.png'}],
    ESRB: {id: 234, igdb:  22345, rating: 1, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_9.svg'},
    yearReleased: 2016,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 29238,
    igdbid: 9812773,
    title: 'Fire Emblem: Three Houses',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1n8t.jpg',
    description: 'Here, order is maintained by the Church of Seiros, which hosts the prestigious Officer’s Academy within its headquarters. You are invited to teach one of its three mighty houses, each comprised of students brimming with personality and represented by a royal from one of three territories. As their professor, you must lead your students in their academic lives and in turn-based, tactical RPG battles wrought with strategic, new twists to overcome. Which house, and which path, will you choose?',
    rating: 94.0,
    released: new Date('06/26/2019'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 4567, igdbid: 23456, name: 'RPG'}, {id: 4789, igdbid: 239106, name: 'Tactical'}, {id: 4008, igdbid: 238123, name: 'TBS'}],
    website: 'https://www.nintendo.com/games/detail/fire-emblem-three-houses-switch',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/srvuccpodxtzhdiltaxi.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/wgoxfasbgocvjf6wvxoj.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ivmxp2d95gugqj6583wr.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/xbfmiaqsxciduahpv6xk.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/qnexghyl8w9dlsj6tyg4.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/vqxowfpq2xurqwfqiffx.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/me3tgarx2lkngxr4dzw6.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ojadhbpnkxvnf3mozeyw.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/ynbji1swyqkg0co3cgag.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/amstvw2qfwncxduyeegb.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ydfmkj8og9xy0fy10bpt.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/uzjlubc1tzcpvi1hx7ai.jpg'],
    platforms: [{id: 234, igdbid: 23456, name: 'Nintendo Switch', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6b.png'}],
    ESRB: {id: 207, igdb:  26485, rating: 2, ratingCover: 'https://www.igdb.com/assets/esrb/esrb_t-addf8c69e4e93438b2a4cf046972279b7f9a6448929fbb0b0b7b7c28a0e60a24.png'},
    yearReleased: 2019,
    created: new Date(),
    modified: new Date()
  }, 
  {
    id: 44444,
    igdbid: 4444444,
    title: 'The Legend of Zelda: The Wind Waker HD',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/xcivov9txngp8jyd0cyd.jpg',
    description: 'The Legend of Zelda: The Wind Waker is the 10th sequel of the Legend of Zelda action-adventure series. It\'s the first game of the series to be set on a group of islands in the sea. Therefore, many of Link\'s actions base on sailing and traveling from island to island, making a baton for controlling the wind the key item of the game. The Legend of Zelda: The Wind Waker HD is a HD remaster of the the cartoonish cel-shaded The Legend of Zelda: The Wind Waker released in 2002 for Gamecube.',
    rating: 91.0,
    released: new Date('09/26/2016'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 1235, igdbid: 12346, name: 'Platform'}, {id: 9308, igdbid: 20272, name: 'Puzzle'}, {id: 4567, igdbid: 23456, name: 'RPG'}],
    website: 'http://zelda.com/windwaker/',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/jq2qnvlctkpgdijoz9wa.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/cbz985vuokf4nr3ea7oy.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ufxcarhopdgganl26on6.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/wdz35ucjwiwr9deibpz1.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/aiu6fl40w05q0q9dbucl.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/dlbt4p89h0kgn68hnzkh.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/wuzwp32ottzgkddskubf.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/tpyrax7hqpg5urexui5d.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/pjtarpcichwkw1mhtoyb.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/zbuxibfkegb0qogxqkt5.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/zkyxfsetxh9usl3ezqbf.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ncjicz8a2zxwa3m6q7el.jpg'],
    platforms: [{id: 111, igdbid: 11111, name: 'WiiU', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6n.png'}],
    ESRB: {id: 234, igdb:  22345, rating: 1, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_9.svg'},
    yearReleased: 2018,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 29838,
    igdbid: 9819203,
    title: 'Ghost Trick: Phantom Detective',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/xyskiae9s9x7l8moh2oi.jpg',
    description: 'Ghost Trick: Phantom Detective is a puzzle/adventure game for the Nintendo DS and iOS. It was developed mainly by Shu Takumi, the man behind the Ace Attorney Series. Game\'s story centers on the protagonist Sissel, and his ghost\'s struggle to discover who he was when he was alive and who killed him. The player assumes the role of this ghost, who has the ability to perform various Ghost Tricks to solve puzzles and navigate the world around him.',
    rating: 86.5,
    released: new Date('06/19/2010'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 9308, igdbid: 202723, name: 'Puzzle'}],
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/liz9o1q5qdwmwexwg2ax.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ohiddpguyc5mgzxwoclv.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/mbydkxyqp5hhnwhdzxdf.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/qspk8dbsqy4dwaluonzq.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/oqgk9q0jogtdudrbsxyx.jpg',
    'https://images.igdb.com/igdb/image/upload/t_original/ixbuauwu2hgyifnqd2kg.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/t9j2c4g9shh3obiuivdr.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/a0rejikz8lzegvlnvity.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/xygjhcct1akjhjajydf0.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/ei6yodoezjjdgl1w7mog.jpg'],
    platforms: [{id: 236, igdbid: 23457, name: 'Nintendo DS', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6r.png'}, {id: 839, igdbid: 93820, name: 'iOS', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6w.png'}],
    yearReleased: 2010,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 80238,
    igdbid: 9819853,
    title: 'Monster Hunter: World',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/fxgwm1nnyexhvauqv0ds.jpg',
    description: 'Monster Hunter: World sees players take on the role of a hunter that completes various quests to hunt and slay monsters within a lively living and breathing eco-system full of predators…. and prey. In the video you can see some of the creatures you can expect to come across within the New World, the newly discovered continent where Monster Hunter: World is set, including the Great Jagras which has the ability to swallow its prey whole and one of the Monster Hunter series favourites, Rathalos. Players are able to utilise survival tools such as the slinger and Scoutfly to aid them in their hunt. By using these skills to their advantage hunters can lure monsters into traps and even pit them against each other in an epic fierce battle. Can our hunter successfully survive the fight and slay the Anjanath? He’ll need to select his weapon choice carefully from 14 different weapon classes and think strategically about how to take the giant foe down. Don’t forget to pack the camouflaging ghillie suit!',
    rating: 91.5,
    released: new Date('01/26/2018'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 4567, igdbid: 23456, name: 'RPG'}],
    website: 'https://www.nintendo.com/games/detail/fire-emblem-three-houses-switch',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/nlkhosogz2ymgk9nypyq.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/afmdmszdechkmzrhq7zm.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/imxdu1yovg9qvv85hidw.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/xcx4gvuehj9qzklnuadu.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ghcjheumz1norh0rwaxk.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/ojdwmo8mhipudkalaxlo.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/oydgjnzydmdfwd3vtmp9.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/nqmwzj4azjunajjlniy8.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/c9rskkieuhapebstfxys.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/u3y9wqhlh2ufby0sb6yt.jpg'],
    platforms: [{id: 123, igdbid: 12345, name: 'PS4', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6e.png'}, {id:281, igdbid: 92019, name: 'PC', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/irwvwpl023f8y19tidgq.png'}],
    ESRB: {id: 207, igdb:  26485, rating: 2, ratingCover: 'https://www.igdb.com/assets/esrb/esrb_t-addf8c69e4e93438b2a4cf046972279b7f9a6448929fbb0b0b7b7c28a0e60a24.png'},
    yearReleased: 2019,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 22222,
    igdbid: 2345998,
    title: 'Super Smash Bros. Ultimate',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1il8.jpg',
    description: 'Legendary game worlds and fighters collide in the ultimate showdown—a new entry in the Super Smash Bros. series for the Nintendo Switch system! New fighters, like Inkling from the Splatoon series and Ridley from the Metroid series, make their Super Smash Bros. series debut alongside every Super Smash Bros. fighter in the series…EVER! Faster combat, new items, new attacks, new defensive options, and more will keep the battle raging whether you’re at home or on the go.',
    rating: 89.0,
    released: new Date('12/07/2018'),
    genres: [{id: 1111, igdbid: 11111, name: 'Fighting'}],
    website: 'https://www.smashbros.com/en_US/index.html',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/sc5rla.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/sc5rl9.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/sc5rl8.jpg',
    'https://images.igdb.com/igdb/image/upload/t_original/sc5rl7.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/sc5rl6.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/sc5rl5.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/mx0rezw9cvublfnbjalm.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/mi0pns4kpvku1mt9rj3c.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/notn8ahnbkglatmokc86.jpg',
    'https://images.igdb.com/igdb/image/upload/t_original/poy3a7v02a5g1wg4usfq.jpg'],
    platforms: [{id: 234, igdbid: 23456, name: 'Nintendo Switch', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6b.png'}],
    ESRB: {id: 234, igdb:  22345, rating: 1, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_9.svg'},
    yearReleased: 2018,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 33333,
    igdbid: 3333333,
    title: 'Tokyo Mirage Sessions #FE',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ite.jpg',
    description: 'Tokyo Mirage Sessions #FE is an crossover role-playing video game in development by Atlus and Intelligent Systems for the Wii U, based on the two companies\' Shin Megami Tensei and Fire Emblem series, respectively',
    rating: 76.0,
    released: new Date('12/26/2015'),
    genres: [{id: 4567, igdbid: 23456, name: 'RPG'}],
    website: 'http://www.nintendo.com/games/detail/tokyo-mirage-sessions-fe-wii-u',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/icvmu3q7dpg1a8raz8gh.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/xiwy3djlqq0pmgrptmof.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/wjjjaernaa2vuiuftyy3.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/qn2fxpmvpouk0vayxuta.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/gcckocff1z69afklw2qh.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/jgreqrbgi3lszyzehckx.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/stuc2wwxphh0l4jcfzb2.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/livbaebnvtmkoukau03z.jpg'],
    platforms: [{id: 111, igdbid: 11111, name: 'WiiU', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6n.png'}],
    ESRB: {id: 207, igdb:  26485, rating: 2, ratingCover: 'https://www.igdb.com/assets/esrb/esrb_t-addf8c69e4e93438b2a4cf046972279b7f9a6448929fbb0b0b7b7c28a0e60a24.png'},
    yearReleased: 2018,
    created: new Date(),
    modified: new Date()
  }
];

export default tempGamesList;