const tempGamesList = [
  {
    id: 12345,
    igdbid: 1234567,
    title: 'Persona 5',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1iea.jpg',
    description: 'Persona 5, a turn-based JRPG with visual novel elements, follows a high school student with a criminal record for a crime he didn\'t commit. Soon he meets several characters who share similar fates to him, and discovers a metaphysical realm which allows him and his friends to channel their pent-up frustrations into becoming a group of vigilantes reveling in aesthetics and rebellion while fighting corruption.',
    rating: 94.5,
    released: new Date('09/15/2016'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 1235, igdbid: 12346, name: 'Platform'}, {id: 4567, igdbid: 23456, name: 'RPG'}],
    website: 'http://www.atlus.com/persona5/home.html',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/hlev27g508rkq1prpghw.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/pm074uf0po31urbrjyxz.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/k9vp7u6khokwawwctcgc.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/gin55k9eyfq8udk0taym.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/tow7qunrq6rvwouracii.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ar4pd.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ar4pc.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ar4pb.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/v095khsskhxfgirwzyfz.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/vnu0tj6shwqgv5gs1hdc.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/zuwsl0kqezzzdzn4dhs4.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/hv41uaug9qpyhf0ecf9a.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/lpcheu5ndticqahdofdy.jpg'],
    platforms: [{id: 123, igdbid: 12345, name: 'PS4', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6e.png'}],
    ESRB: {id: 123, igdb:  12345, rating: 3, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_11.svg'},
    yearReleased: 2016,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 23456,
    igdbid: 2345678,
    title: 'The Legend of Zelda: Breath of the Wild',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/mievpzb9rbzzenmznvnr.jpg',
    description: 'Step into a world of discovery, exploration and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series. Travel across fields, through forests and to mountain peaks as you discover what has become of the ruined kingdom of Hyrule in this stunning open-air adventure.',
    rating: 95.5,
    released: new Date('03/03/2017'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 4567, igdbid: 23456, name: 'RPG'}],
    website: 'http://www.zelda.com/breath-of-the-wild/',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/ods1wksjfo9h0v7fpigo.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ayjm7juog9vitiwbfrcz.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/gcdqd20hi1wgmguu3reg.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/eirwofgnucvx7h87svr2.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/mftmubfp9ntwbreejfi7.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/qoytovwmzj70nufwxb2r.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/bf4ag3vxlfnv0nhhplga.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/mepn5qujlccdlkhfkwr8.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/tjlglyti9pi4cowyiact.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/vbs1btl6ts17zeos4g5v.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/djytg7kqip9d5dgekfew.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ngyp9tw3elpfdngwc00i.jpg'],
    platforms: [{id: 234, igdbid: 23456, name: 'Nintendo Switch', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6b.png'}],
    ESRB: {id: 234, igdb:  22345, rating: 1, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_9.svg'},
    yearReleased: 2017,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 23457,
    igdbid: 4345678,
    title: 'Ace Attorney Investigations 2',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/nz4t3kgz9w9nf0e9qumo.jpg',
    description: 'Gyakuten Kenji 2 (逆転検事 2 Gyakuten Kenji 2, lit. "Turnabout Prosecutor 2""), also referred to as "Ace Attorney Investigations 2" by Capcom staff, is the sequel to "Gyakuten Kenji" (known as "Ace Attorney Investigations: Miles Edgeworth" in English) and the sixth game in the "Ace Attorney" series of text adventure video games.',
    rating: 99.0,
    released: new Date('02/03/2011'),
    genres: [],
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/frgknqca1xyot7fyzw4j.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/cxf2bt9ejnkbeocuoym7.jpg' , 'https://images.igdb.com/igdb/image/upload/t_original/qx0ckbpgu5i0y7tmpxha.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/biza3bnqypn0zb3zljzt.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/zlotf0jcvnw6c4ldyzqa.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/nyoj0jhufbri0ql6fsin.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/v9fzxl9nggsfllmzeptj.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/frgknqca1xyot7fyzw4j.jpg'],
    platforms: [{id: 236, igdbid: 23457, name: 'Nintendo DS', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6r.png'}],
    yearReleased: 2011,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 29387,
    igdbid: 9834753,
    title: 'Stardew Valley',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/xrpmydnu9rpxvxfjkiu7.jpg',
    description: 'Stardew Valley is an open-ended country-life RPG! You’ve inherited your grandfather’s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home? It won’t be easy. Ever since Joja Corporation came to town, the old ways of life have all but disappeared. The community center, once the town’s most vibrant hub of activity, now lies in shambles. But the valley seems full of opportunity. With a little dedication, you might just be the one to restore Stardew Valley to greatness!',
    rating: 89.5,
    released: new Date('02/26/2016'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 4567, igdbid: 23456, name: 'RPG'}],
    website: 'http://www.stardewvalley.net/',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/rhxs1x9w5hf5kde2osf5.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/sw7rtba7p1xs77klsime.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/iwswpvxa9ytrpk8yjcyx.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/ak7zmag7zztpqha1jjde.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/g1aakqbkp2quq0krqeky.jpg'],
    platforms: [{id: 234, igdbid: 23456, name: 'Nintendo Switch', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6b.png'}, {id:840, igdbid: 92330, name: 'Steam', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6i.png'}],
    ESRB: {id: 234, igdb:  22345, rating: 1, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_9.svg'},
    yearReleased: 2016,
    created: new Date(),
    modified: new Date()
  },
  {
    id: 29398,
    igdbid: 9834773,
    title: 'Minecraft',
    cover: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ml9.jpg',
    description: 'Minecraft is an open world game that has no specific goals for the player to accomplish, allowing players a large amount of freedom in choosing how to play the game however, there is an achievement system. The gameplay by default is first person, but players have the option to play in third person mode. The core gameplay revolves around breaking and placing blocks. The game world is essentially composed of rough 3D objects—mainly cubes—that are arranged in a fixed grid pattern and represent different materials, such as dirt, stone, various ores, water, and tree trunks. While players can move freely across the world, objects and items can only be placed at fixed locations relative to the grid. Players can gather these material blocks and place them elsewhere, thus allowing for various constructions.',
    rating: 83.0,
    released: new Date('10/07/2011'),
    genres: [{id: 1234, igdbid: 12345, name: 'Adeventure'}, {id: 4568, igdbid: 23556, name: 'Arcade'}, {id: 4569, igdbid: 23956, name: 'Indie'}, {id: 4268, igdbid: 23526, name: 'Simulator'}, {id: 4478, igdbid: 23592, name: 'Strategy'}],
    website: 'https://minecraft.net/',
    screenshots: ['https://images.igdb.com/igdb/image/upload/t_original/vm8dthz69tuppu1pazjc.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/kvbwjprt8tnweegegv3u.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/risbtotrixghfy8o9wdj.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/cf4mbecc1blh5k3rlszr.jpg', 
    'https://images.igdb.com/igdb/image/upload/t_original/ldeuxkt76th569psyzhq.jpg', 'https://images.igdb.com/igdb/image/upload/t_original/c5ofbzndvfgpclfra7cq.jpg', ''],
    platforms: [{id: 202, igdbid: 23296, name: 'Xbox 360', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/pl6z.png'}, {id:281, igdbid: 92019, name: 'PC', logo: 'https://images.igdb.com/igdb/image/upload/t_logo_med/irwvwpl023f8y19tidgq.png'}],
    ESRB: {id: 234, igdb:  22345, rating: 1, ratingCover: 'https://next.igdb.com/images/esrb/ratingsymbol_9.svg'},
    yearReleased: 2016,
    created: new Date(),
    modified: new Date()
  }
];

export default tempGamesList;